config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/webhooks/telegram_vbc43edbf1614a075954dvd4bfab34l1' => 'webhooks#callback'

  post "post_message" , to: "admin#post_message"
  get "approve_dealer/:id" , to: "admin#approve_dealer"
  get "denied_dealer/:id" , to: "admin#denied_dealer"
  get "del_channel/:id" , to: "admin#del_channel"
  get "ban_dealer/:id" , to: "admin#ban_dealer"
  get "send_message" , to: "admin#send_message"
  get "photo" ,  to: "admin#get_photo"
  get "photo_url" ,  to: "admin#get_photo_url"
  get "users", to: "admin#users"
  get "shoka_channel", to: "admin#shoka_channel"
  root  'application#index'
  resources :channels
  end

app/models/channel.rb
class Channel < ApplicationRecord
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
        @channels = Channel.all
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'הערוץ נוסף בהצלחה!' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'הערוץ עודכן בהצלחה!' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'הערוץ הוסר בהצלחה!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
   params.require(:channel).permit(:name, :link,)
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= form_with(model: channel, local: true) do |form| %>
<style>
table#customers {
    font-size:12px;
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    border-spacing: 0;
    width: 75%;
    margin-right: auto;
    margin-left: auto;
}

#customers td, #customers th {
    border: 1px solid #ddd;
    text-align: center;
    padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2}

#customers th {
    padding-top: 11px;
    padding-bottom: 11px;
    background-color: #454545;
    color: white;
}
#main {
    padding-top: 11px;
    padding-bottom: 11px;
    background-color: #000000;
    color: white;
}
	body {
		background-color: #cacaca;
	}

</style>
<table id="customers">
<tbody>
    <tr style="height: 2px;">   
    <th colspan="9">
    <img src="https://i.imgur.com/AXsKkzf.jpg" width="260" height="150" align="right" alt="מערכת ניהול " />
    </th> 
    </tr>
    <tr style="height: 2px;">   
    <th colspan="6" style="height: 2px; text-align: right;color: #FFFFFF;font-size:14px;text-decoration: none;">
    <a href="/users" style="height: 2px; text-align: right;color: #FFFFFF;font-size:14px;text-decoration: none;"><b>ניהול משתמשים</b></a>&nbsp;|
        <a href="/channels" style="height: 2px; text-align: right;color: #FFFFFF;font-size:14px;text-decoration: none;"><b>רשימת ערוצים</b></a>&nbsp;|
     <a href="/send_message" style="height: 2px; text-align: right;color: #FFFFFF;font-size:14px;text-decoration: none;"><b>שליחת הודעות למשתמשים</b></a>
    </th> 
    </tr>
<tr>
      <tr>
<td align="right">
    <input type="text" name="Channel_id" value="<%= channel.id %>" disabled>
</td>
<td>
<b>:ID</b>
</td>
      </tr>
<td align="right">
<%= form.text_field :name %>
</td>
<td>
<b>:שם הערוץ</b>
</td>
      </tr>
            <tr>
<td align="right">
<%= form.text_field :link %>
</td>
<td>
<b>:לינק הערוץ</b>
</td>
      </tr>
</tr>
          <tr style="height: 2px;">   
    <th colspan="9">
        <% if channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
       </th> 
    </tr>
</tbody></table>

app/views/channels/edit.html.erb
<%= render 'form', channel: @channel %>

app/views/channels/index.html.erb
<style>
table#customers {
    font-size:12px;
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    border-spacing: 0;
    width: 75%;
    margin-right: auto;
    margin-left: auto;
}

#customers td, #customers th {
    border: 1px solid #ddd;
    text-align: center;
    padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2}

#customers th {
    padding-top: 11px;
    padding-bottom: 11px;
    background-color: #454545;
    color: white;
}
#main {
    padding-top: 11px;
    padding-bottom: 11px;
    background-color: #000000;
    color: white;
}
	body {
		background-color: #cacaca;
	}

</style>
<table id="customers">
<tbody>
    <tr style="height: 2px;">   
    <th colspan="9">
    <img src="https://i.imgur.com/AXsKkzf.jpg" width="260" height="150" align="right" alt="מערכת ניהול " />
    </th> 
    </tr>
    <tr style="height: 2px;">   
    <th colspan="7" style="height: 2px; text-align: right;color: #FFFFFF;font-size:14px;text-decoration: none;">
    <a href="/users" style="height: 2px; text-align: right;color: #FFFFFF;font-size:14px;text-decoration: none;"><b>ניהול משתמשים</b></a>&nbsp;|
        <a href="/channels" style="height: 2px; text-align: right;color: #FFFFFF;font-size:14px;text-decoration: none;"><b>רשימת ערוצים</b></a>&nbsp;|
     <a href="/send_message" style="height: 2px; text-align: right;color: #FFFFFF;font-size:14px;text-decoration: none;"><b>שליחת הודעות למשתמשים</b></a>
    </th> 
    </tr>
    <tr style="height: 2px;">   
    <th colspan="7">
     <p id="notice"><%= notice %></p>
    </th> 
<tr>
    <th>הסר ערוץ</th>
    <th>ערוך ערוץ</th>
    <th>הצג ערוץ</th>
    <th>נוצר בתאריך</th>
    <th>קישור לערוץ</th>
    <th>שם הערוץ</th>
    <th>ID</th>
</tr>
    <%= @channels.each do |channel| %>
<tr>
      <tr>
<td><%= link_to image_tag("https://i.imgur.com/tWgffNV.png", height: '15', width: '15'), channel, method: :delete, data: { confirm: 'האם אתה בטוח שברצונך למחוק?' } %></td>
    <td><%= link_to image_tag("https://png.icons8.com/office/1600/edit-property.png", height: '15', width: '15'), edit_channel_path(channel) %></td>
    <td><%= link_to image_tag("https://png.icons8.com/ultraviolet/2x/about.png", height: '15', width: '15'), channel %></td>
     <td><%= channel.created_at %></td>
    <td><%= channel.link %></td>
    <td><%= channel.name %></td>
    <td><b><u><%= channel.id %></u></b></td>
      </tr>
</tr>
    <% end %>   
        <tr style="height: 2px;">   
    <th colspan="7" style="height: 2px; text-align: center;color: #FFFFFF;font-size:14px;text-decoration: none;"><a href="channels/new" style="height: 2px; text-align: right;color: #FFFFFF;font-size:14px;text-decoration: none;"><b>הוסף ערוץ חדש</b></a></th> 
    </tr>
</tbody></table>

app/views/channels/new.html.erb
<%= render 'form', channel: @channel %>

app/views/channels/show.html.erb
<style>
table#customers {
    font-size:12px;
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    border-spacing: 0;
    width: 75%;
    margin-right: auto;
    margin-left: auto;
}

#customers td, #customers th {
    border: 1px solid #ddd;
    text-align: center;
    padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2}

#customers th {
    padding-top: 11px;
    padding-bottom: 11px;
    background-color: #454545;
    color: white;
}
#main {
    padding-top: 11px;
    padding-bottom: 11px;
    background-color: #000000;
    color: white;
}
	body {
		background-color: #cacaca;
	}

</style>
<table id="customers">
<tbody>
    <tr style="height: 2px;">   
    <th colspan="4">
    <img src="https://i.imgur.com/AXsKkzf.jpg" width="260" height="150" align="right" alt="מערכת ניהול " />
    </th> 
    </tr>
    <tr style="height: 2px;">   
    <th colspan="4" style="height: 2px; text-align: right;color: #FFFFFF;font-size:14px;text-decoration: none;">
    <a href="/users" style="height: 2px; text-align: right;color: #FFFFFF;font-size:14px;text-decoration: none;"><b>ניהול משתמשים</b></a>&nbsp;|
        <a href="/channels" style="height: 2px; text-align: right;color: #FFFFFF;font-size:14px;text-decoration: none;"><b>רשימת ערוצים</b></a>&nbsp;|
     <a href="/send_message" style="height: 2px; text-align: right;color: #FFFFFF;font-size:14px;text-decoration: none;"><b>שליחת הודעות למשתמשים</b></a>
    </th> 
    </tr>
    <th>אנשים בערוץ</th>
    <th>קישור לערוץ</th>
    <th>שם הערוץ</th>
    <th>ID</th>
</tr>    
<tr>
      <tr>
    <td><font size="3" color="red"><b>12,544</b></font></td>
    <td><%= @channel.link %></td>
    <td><%= @channel.name %></td>
    <td><b><u><%= @channel.id %></u></b></td>
      </tr>
</tr>    
        <tr style="height: 2px;">   
    <th colspan="4"></th> 
    </tr>
</tbody></table>